function init_language_en()
{
    xml["en"] = {
        "ok" : "OK",
        "cancel" : "Cancel",
        "reset" : "Restore",
        "save" : "Save",
        "tip" : "Prompt",
        "click" : "Left Button",
        "menu" : "Right Button",
        "mid" : "Middle Button",
        "forward" : "Forward",
        "back" : "Backward",
        "sr" : "Scroll Up",
        "sd" : "Scroll Down",
        "tl" : "左摆",
        "tr" : "右摆",
        "dclick" : "双击",
        "macro" : "Macro",
        "media" : "Multimedia",
        "combo" : "Shortcut",
        "dpi" : "DPI Loop",
        "fire" : "Fire Key",
        "off" : "Disable",
        "mouse" : "Mouse",
        "keyboard" : "Keyboard",

        "fire1" : "Keep left-clicking according to the interval and times",
        "fire2" : "interval",
        "fire3" : "ms",
        "fire4" : "loop",
        "fire5" : "times",
        "fire6" : "When the number of times is set to 0, press the button to keep firing and release the button to finish",

        "mac1" : "New",
        "mac2" : "Import",
        "mac3" : "Cycle until the key is released",
        "mac4" : "Cycle until any key is pressed",
        "mac5" : "Cycle",
        "mac6" : "Recording",
        "mac7" : "Stop",
        "mac8" : "Cycle",
        "mac9" : "Content",
        "mac10" : "Modify key",
        "mac11" : "Modify delay",

        "media1" : "Media Player",
        "media2" : "Play/Pause",
        "media3" : "Stop",
        "media4" : "Previous Track",
        "media5" : "Next Track",
        "media6" : "Volume+",
        "media7" : "Volume-",
        "media8" : "Mute",
        "media9" : "Calculator",
        "media10" : "EMail",
        "media11" : "Browser",
        "media12" : "My Computer",
        "media13" : "收藏夹",
        "media14" : "Refresh",
        "media15" : "Search",
        "media16" : "WWW Stop",
        "media17" : "WWW Forward",
        "media18" : "WWW Backward",

        "msg1" : "Device",
        "msg2" : "Button",
        "msg3" : "Performance",
        "msg4" : "Others",
        "msg5" : "System",
        "msg6" : "Keyboard",
        "msg7" : "Special",
        "msg8" : "Macro",
        "msg9" : "Settings",
        "msg10" : "Onboard File",
        "msg11" : "Onboard",
        "msg12" : "On-premise configuration",
        "msg13" : "+ New Profile",
        "msg14" : "DPI Settings",
        "msg15" : "New Stage",
        "msg16" : "DPI is the mouse movement speed, modify the DPI setting by editing or dragging the slider above",
        "msg17" : "Report Rate",
        "msg18" : "Setting the frequency of communication between the mouse and the computer and increasing the polling rate can reduce latency, but increase some power consumption",
        "msg19" : "A high polling rate will have certain requirements for the CPU performance and memory frequency of the computer, and the computer with low configuration may have stuttering or fail to achieve the preset return rate",
        "msg20" : "Performance mode",
        "msg21" : "HP",
        "msg22" : "Corded",
        "msg23" : "LP",
        "msg24" : "The sensor performs at its best when gaming mode is on, but consumes more power",
        "msg25" : "Note: 8K is already the best performance, and it is not possible to turn on game mode",
        "msg26" : "LOD",
        "msg27" : "Sets the minimum working height of the sensor when the mouse is raised",
        "msg28" : "Motion sync",
        "msg29" : "The sleek algorithm correction is carried out on the mouse movement, and the movement trajectory is more accurate",
        "msg31" : "Angle snapping",
        "msg32" : "When the mouse moves in a straight line, the jitter is corrected and becomes an absolute straight line movement (it is not recommended to enable it in the game)",
        "msg33" : "Ripple control",
        "msg34" : "Algorithm correction for high movement speed to eliminate wavy jitter (it is not recommended to enable it in the game)",
        "msg35" : "Receiver Pairing",
        "msg36" : "1K or 8K Receiver Pairing",
        "msg37" : "Pairing",
        "msg38" : "All settings will be restored to factory state, please operate with caution",
        "msg39" : "Restore",
        "msg40" : "This will erase all settings, are you sure you want to reset?",
        "msg41" : "Create Profile",
        "msg42" : "A new profile will be created with the current onboard",
        "msg43" : "Please enter a profile name",
        "msg44" : "Profile switch",
        "msg45" : "Go and settings",
        "msg46" : "Delete",
        "msg47" : "There is currently only one left button, and you may not be able to click after changing it",
        "msg48" : "Continue to change",
        "msg49" : "Edit",
        "msg50" : "Please select a button first.",
        "msg51" : "At least one DPI should be retained.",
        "msg52" : "The maximum DPI level has been reached.",
        "msg53" : "Please wait, the data is being updated",
        "msg54" : "Settings failed.",
        "msg55" : "Export",
        "msg56" : "Import failed.",
        "msg57" : "The maximum number of keys has been reached.",
        "msg58" : "Are you sure you want to update the configuration to ",
        "msg59" : "XY is adjusted separately",
        "msg60" : "X-Axis",
        "msg61" : "Y-Axis",
        "msg62" : "Invert the left and right button",
        "msg63" : "Receiver LED",
        "msg64" : "Connect and polling rate",
        "msg65" : "Battery status",
        "msg66" : "Battery warning",
        "msg67" : "Debounce",
        "msg68" : "If a double click occurs, set the debounce to 8ms or higher until there is no double click",
        "msg69" : "Warning: double click may occur when the latency is lowered",
        "msg70" : "Dormancy time",
        "msg71" : "The time it takes for the mouse to go to sleep after it is idle",
        "msg72" : "Balancing optimal performance and optimal battery life and energy efficiency, suitable for daily use such as office work",
        "msg73" : "The sensor has the lowest energy efficiency, the lowest power consumption, and the longest battery life",
        "msg74" : "Are you sure you want to delete it?",
        "msg75" : "When the mouse is connected to the receiver, a different colour is displayed depending on the USB polling rate.，Red(125Hz)，Blue(250Hz)，Yellow(500Hz)，Orange(1000Hz)，Purple(2000Hz)，Green(4000Hz)，White(8000Hz)",
        "msg76" : "Depending on the current battery level of the mouse, gradually change from green (100%), yellow (66%), orange (33%), and red (0%).",
        "msg77" : "Always keep it off and only flash red when the mouse needs to be charged.",
        "msg78" : "Please wait, initialising.",
        "msg79" : "This profileThe profile does not apply to the current device.",
        "msg80" : "Levels",

        // "msg81" : "Firmware & driver upgrades",
        "msg81":"Firmware Download",
        "msg82" : "Web Firmware",
        "msg83" : "Bluetooth Firmware",
        "msg84" : "Upgrade operation steps:",
        "msg85" : "Steps for mouse WEB firmware upgrade:",
        "msg86" : "Connect the mouse to the computer via cable, click 'Mouse Upgrade,' and wait for the upgrade to complete;",
        "msg87" : "Plug the receiver into the computer, click 'Receiver Upgrade,' and wait for the upgrade to complete;",
        "msg88" : "Friendly Reminder: If the mouse fails to move, please re-pair the code.",
        "msg89" : "Mouse Bluetooth Firmware Upgrade:",
        "msg90" : "Just connect the mouse to the computer via cable, click 'Mouse Upgrade,' and wait for the upgrade to complete.",
        "msg91" : "Ghero Series",
        "msg92" : "Tips: It takes a certain amount of time for the mouse information to be synchronized before the interface displays the mouse power.",
        "msg93" : "",
        "msg94" : "Zero 29 Series",
        "msg95" : "Zero 39 Series",
        "msg96" : "G23V2 Series",
        "msg97" : "G23 Series",
        "msg98" : "G24 Series",
        "msg99" : "Ghero Series Dedicated(1.4.0.3)",
        "msg100" : "G23 Series Dedicated(1.4.0.3)",
        "msg101" : "G24 Series Dedicated(1.4.0.3)",
        "msg102" : "Zero 29 Series Dedicated(1.4.0.3)",
        "msg103" : "Zero 39 Series Dedicated(1.4.0.3)",
        "msg104" : "Ghero Series Bluetooth Firmware",
        "msg105" : "G23 Series Bluetooth Firmware",
        "msg106" : "G24 Series Bluetooth Firmware",
        "msg107" : "Zero 29 Series Bluetooth Firmware",
        "msg108" : "Zero 39 Series Bluetooth Firmware",
        "msg109" : "download firmware",
        "msg110" : "G23V2 Series Dedicated Firmware(1.4.0.3)",
        "msg111" : "G23V2 Series Bluetooth Firmware",
        "msg112" : "Ghero Series APP Firmware",
        "msg113" : "G23 Series APP Firmware",
        "msg114" : "G24 Series APP Firmware",
        "msg115" : "Zero 29 Series APP Firmware",
        "msg116" : "Zero 39 Series APP Firmware",
        "msg117" : "G23V2 Series APP Firmware",
        "msg118" : "The upgrade enables the APP driver to save up to 4 switchable configurations. The 3950 version mouse adds a 20,000fps polling rate setting.",
        "msg119" : "After upgrading the G23 series to the dedicated firmware (1.4.0.3), install this driver.",
        "msg120" : "The upgrade supports Bluetooth connectivity for the mouse.",
        "msg121" : "download driver",

        "wec1" : "Welcome to the incott web driver",
        "wec2" : "Here you can quickly configure your Incott device and customize your device to your liking",
        "wec3" : "Once the configuration is complete, all you need to do is save, close, and enjoy。",
        "wec4" : "Only Chrome and Edge browsers are supported, and devices G23/G24/G23V2/零29/零39 are currently supported",
        "wec5" : "More devices are being adapted...",
        "wec6" : "Initialize device",
        "wec7" : "Buy Incott product",
        "wec8" : "Connect",
        "wec9" : "Allow",
        "wec10" : "Setting",
        "wec11" : "Allow the browser to connect to your device",
        "wec12" : "This will open a list of devices next to the URL bar, select your device in the list and click \"Connect\"",
        "wec13" : "Allow browser access",
        "wec14" : "If your device doesn't show up, plug it back in and try again",
        "wec15" : "Receiver pairing",
        "wec16" : "Pairing",
        "wec17" : "Scheme",
        "wec18" : "Light",
        "wec19" : "Dark",
        "wec20" : "Language",
        "wec21" : "Feedback",
        "wec22" : "Got a question? Click Feedback",
        "wec23" : "UI",
        "wec24" : "Firmware",
        "wec25" : "Pairing",
        "wec26" : "Back",

        "wec27" : "Please select a store below to purchase",
        "wec28" : "Tmall",
        "wec29" : "Taobao",
        "wec30" : "TikTok",
        "wec31" : "JD",

        "wec32" : "Recommended PC configuration",
        "wec33" : "To ensure a high polling rate user experience, please ensure that your computer configuration meets the following minimum recommended configuration requirements in order to maximize the performance of the mouse",
        "wec34" : "Intel Platform<br>CPU: i7 9700k or above<br>GPU: NVIDIA GTX1080 or above<br>RAM: 16GB or above",
        "wec35" : "AMD Platform<br>CPU: 3600X or above<br>GPU: AMD RX5700 or above<br>RAM: 16GB or above",
        "wec36" : "Monitor: Screen refresh rate above 240Hz",
        "wec37" : "* If there is a frame loss or disconnection after enabling<br> the 8K polling rate, you can consult customer service",
        "wec38" : "I got it",

        "wec39" : "Tmall",
        "wec40" : "Taobao",
        "wec41" : "TikTok",
        "wec42" : "JD",
        "wec43" : "PINK",
    };
}
